<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class InstitutionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('institutions')->delete();
        
        \DB::table('institutions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Louvre Museum',
                'description' => 'The world\'s largest art museum and a historic monument in Paris',
                'address' => 'Rue de Rivoli, 75001',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.86060000',
                'longitude' => '2.33760000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'British Museum',
                'description' => 'Public museum dedicated to human history, art and culture',
                'address' => 'Great Russell St, London WC1B 3DG',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.51940000',
                'longitude' => '-0.12700000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Metropolitan Museum of Art',
                'description' => 'The largest art museum in the United States',
                'address' => '1000 5th Ave, New York, NY 10028',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.77940000',
                'longitude' => '-73.96320000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Latvian National Museum of Art',
                'description' => 'The richest collection of national art in Latvia',
                'address' => 'Jaņa Rozentāla laukums 1',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.95480000',
                'longitude' => '24.11410000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Prado Museum',
                'description' => 'Spain\'s main national art museum',
                'address' => 'Calle de Ruiz de Alarcón, 23, 28014 Madrid',
                'city' => 'Madrid',
                'country' => 'Spain',
                'latitude' => '40.41380000',
                'longitude' => '-3.69210000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Uffizi Gallery',
                'description' => 'Prominent art museum in Florence',
                'address' => 'Piazzale degli Uffizi, 6, 50122 Firenze',
                'city' => 'Florence',
                'country' => 'Italy',
                'latitude' => '43.76870000',
                'longitude' => '11.25690000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'The Ritz Paris',
                'description' => 'Luxury hotel in the heart of Paris',
                'address' => '15 Place Vendôme, 75001',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.86820000',
                'longitude' => '2.32850000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.90',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'The Savoy',
                'description' => 'Iconic luxury hotel on the Strand',
                'address' => 'Strand, London WC2R 0EZ',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.51040000',
                'longitude' => '-0.12040000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Grand Hotel Riga',
                'description' => 'Historic luxury hotel in Riga',
                'address' => 'Aspazijas bulvāris 22',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.95110000',
                'longitude' => '24.11210000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Hotel Plaza Athénée',
                'description' => 'Luxury hotel on Avenue Montaigne',
                'address' => '25 Avenue Montaigne, 75008',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.86610000',
                'longitude' => '2.30480000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Le Jules Verne',
                'description' => 'Michelin-starred restaurant in the Eiffel Tower',
                'address' => 'Avenue Gustave Eiffel, 75007',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.85830000',
                'longitude' => '2.29450000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.90',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Sketch',
                'description' => 'Quirky restaurant and afternoon tea venue',
                'address' => '9 Conduit St, London W1S 2XG',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.51360000',
                'longitude' => '-0.14100000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Vincents',
                'description' => 'Fine dining restaurant in Riga',
                'address' => 'Elizabetes iela 19',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.95480000',
                'longitude' => '24.11670000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Osteria Francescana',
                'description' => 'Three Michelin star restaurant',
                'address' => 'Via Stella, 22, 41121 Modena',
                'city' => 'Modena',
                'country' => 'Italy',
                'latitude' => '44.64710000',
                'longitude' => '10.92520000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '5.00',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Eleven Madison Park',
                'description' => 'Fine dining restaurant in Manhattan',
                'address' => '11 Madison Ave, New York, NY 10010',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.74250000',
                'longitude' => '-73.98710000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Café de Flore',
                'description' => 'Historic café in Saint-Germain-des-Prés',
                'address' => '172 Boulevard Saint-Germain, 75006',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.85420000',
                'longitude' => '2.33200000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Caffè Florian',
                'description' => 'Historic café in St Mark\'s Square',
                'address' => 'Piazza San Marco, 57, 30124 Venezia',
                'city' => 'Venice',
                'country' => 'Italy',
                'latitude' => '45.43380000',
                'longitude' => '12.33780000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Miit Coffee',
                'description' => 'Specialty coffee shop in Riga',
                'address' => 'Tērbatas iela 41/43',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.95770000',
                'longitude' => '24.12110000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Blue Bottle Coffee',
                'description' => 'Artisanal coffee roaster and retailer',
                'address' => '450 W 15th St, New York, NY 10011',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.74250000',
                'longitude' => '-74.00710000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Harry\'s New York Bar',
                'description' => 'Historic cocktail bar in Paris',
                'address' => '5 Rue Daunou, 75002',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.86930000',
                'longitude' => '2.33180000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'The American Bar',
                'description' => 'Legendary cocktail bar at The Savoy',
                'address' => 'Strand, London WC2R 0EZ',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.51040000',
                'longitude' => '-0.12040000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Skyline Bar',
                'description' => 'Rooftop bar with panoramic views',
                'address' => 'Elizabetes iela 55',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.96150000',
                'longitude' => '24.12130000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Galeries Lafayette',
                'description' => 'Upscale French department store',
                'address' => '40 Boulevard Haussmann, 75009',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.87380000',
                'longitude' => '2.33200000',
                'category' => 'shop',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Harrods',
                'description' => 'Luxury department store in Knightsbridge',
                'address' => '87-135 Brompton Rd, London SW1X 7XL',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.49940000',
                'longitude' => '-0.16320000',
                'category' => 'shop',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Stockmann',
                'description' => 'Department store in central Riga',
                'address' => '13. janvāra iela 8',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.94960000',
                'longitude' => '24.11630000',
                'category' => 'shop',
                'image_url' => NULL,
                'rating' => '4.40',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Macy\'s Herald Square',
                'description' => 'Iconic department store in Manhattan',
                'address' => '151 W 34th St, New York, NY 10001',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.75080000',
                'longitude' => '-73.98970000',
                'category' => 'shop',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Vatican Museums',
                'description' => 'Public art and sculpture museums in Vatican City',
                'address' => 'Viale Vaticano, 00165 Roma',
                'city' => 'Rome',
                'country' => 'Italy',
                'latitude' => '41.90650000',
                'longitude' => '12.45360000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Hermitage Museum',
                'description' => 'Museum of art and culture in Saint Petersburg',
                'address' => 'Palace Square, 2',
                'city' => 'Saint Petersburg',
                'country' => 'Russia',
                'latitude' => '59.93980000',
                'longitude' => '30.31460000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Rijksmuseum',
                'description' => 'Dutch national museum dedicated to arts and history',
                'address' => 'Museumstraat 1, 1071 XX Amsterdam',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
                'latitude' => '52.36000000',
                'longitude' => '4.88520000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'National Museum of China',
                'description' => 'Museum of Chinese art and history',
                'address' => '16 East Chang\'an Avenue',
                'city' => 'Beijing',
                'country' => 'China',
                'latitude' => '39.90420000',
                'longitude' => '116.39740000',
                'category' => 'museum',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Burj Al Arab',
                'description' => 'Luxury hotel on an artificial island',
                'address' => 'Jumeirah St, Dubai',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'latitude' => '25.14130000',
                'longitude' => '55.18530000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.90',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Marina Bay Sands',
                'description' => 'Integrated resort with iconic rooftop',
                'address' => '10 Bayfront Ave',
                'city' => 'Singapore',
                'country' => 'Singapore',
                'latitude' => '1.28340000',
                'longitude' => '103.86070000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'The Plaza Hotel',
                'description' => 'Luxury hotel and landmark in Manhattan',
                'address' => 'Fifth Avenue at Central Park South',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.76440000',
                'longitude' => '-73.97440000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Raffles Hotel',
                'description' => 'Colonial-style luxury hotel',
                'address' => '1 Beach Rd',
                'city' => 'Singapore',
                'country' => 'Singapore',
                'latitude' => '1.29460000',
                'longitude' => '103.85400000',
                'category' => 'hotel',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Noma',
                'description' => 'Two Michelin star restaurant',
                'address' => 'Refshalevej 96',
                'city' => 'Copenhagen',
                'country' => 'Denmark',
                'latitude' => '55.69610000',
                'longitude' => '12.61130000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.90',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'El Celler de Can Roca',
                'description' => 'Three Michelin star restaurant',
                'address' => 'Carrer de Can Sunyer, 48',
                'city' => 'Girona',
                'country' => 'Spain',
                'latitude' => '41.97940000',
                'longitude' => '2.82140000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.90',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Sukiyabashi Jiro',
                'description' => 'Three Michelin star sushi restaurant',
                'address' => 'Tsukamoto Sogyo Building B1F',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'latitude' => '35.66840000',
                'longitude' => '139.76380000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '5.00',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'The French Laundry',
                'description' => 'Three Michelin star French restaurant',
                'address' => '6640 Washington St',
                'city' => 'Yountville',
                'country' => 'United States',
                'latitude' => '38.40240000',
                'longitude' => '-122.36250000',
                'category' => 'restaurant',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Café Central',
                'description' => 'Traditional Viennese coffeehouse',
                'address' => 'Herrengasse 14',
                'city' => 'Vienna',
                'country' => 'Austria',
                'latitude' => '48.21040000',
                'longitude' => '16.36500000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Café Tortoni',
                'description' => 'Historic café in Buenos Aires',
                'address' => 'Av. de Mayo 825',
                'city' => 'Buenos Aires',
                'country' => 'Argentina',
                'latitude' => '-34.60880000',
                'longitude' => '-58.37560000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.50',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Café Majestic',
                'description' => 'Belle Époque café in Porto',
                'address' => 'Rua Santa Catarina 112',
                'city' => 'Porto',
                'country' => 'Portugal',
                'latitude' => '41.14960000',
                'longitude' => '-8.61090000',
                'category' => 'cafe',
                'image_url' => NULL,
                'rating' => '4.60',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Employees Only',
                'description' => 'Speakeasy-style cocktail bar',
                'address' => '510 Hudson St',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.73390000',
                'longitude' => '-74.00620000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Artesian',
                'description' => 'Award-winning cocktail bar',
                'address' => '1C Portland Pl',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.51860000',
                'longitude' => '-0.14360000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.80',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Bar Hemingway',
                'description' => 'Legendary bar at the Ritz Paris',
                'address' => '15 Place Vendôme',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.86820000',
                'longitude' => '2.32850000',
                'category' => 'bar',
                'image_url' => NULL,
                'rating' => '4.70',
                'user_id' => NULL,
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
            ),
        ));
        
        
    }
}