<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Place;
use App\Models\Institution;

class PlacesAndInstitutionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Places
        $places = [
            [
                'name' => 'Eiffel Tower',
                'description' => 'Iconic iron lattice tower on the Champ de Mars in Paris',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8584,
                'longitude' => 2.2945,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Central Park',
                'description' => 'Large public park in Manhattan, New York City',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7829,
                'longitude' => -73.9654,
                'category' => 'park',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Colosseum',
                'description' => 'Ancient amphitheatre in the centre of Rome',
                'city' => 'Rome',
                'country' => 'Italy',
                'latitude' => 41.8902,
                'longitude' => 12.4922,
                'category' => 'landmark',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Big Ben',
                'description' => 'The Great Bell of the clock at the north end of the Palace of Westminster',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5007,
                'longitude' => -0.1246,
                'category' => 'landmark',
                'rating' => 4.6,
                'image_url' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Riga Old Town',
                'description' => 'Historic centre and a UNESCO World Heritage Site',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9496,
                'longitude' => 24.1052,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1593659039409-c2e4f3e6c636?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Statue of Liberty',
                'description' => 'Colossal neoclassical sculpture on Liberty Island',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.6892,
                'longitude' => -74.0445,
                'category' => 'landmark',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1569098644584-210bcd375b59?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Taj Mahal',
                'description' => 'Ivory-white marble mausoleum in Agra',
                'city' => 'Agra',
                'country' => 'India',
                'latitude' => 27.1751,
                'longitude' => 78.0421,
                'category' => 'landmark',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Great Wall of China',
                'description' => 'Ancient series of fortifications in northern China',
                'city' => 'Beijing',
                'country' => 'China',
                'latitude' => 40.4319,
                'longitude' => 116.5704,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Machu Picchu',
                'description' => '15th-century Inca citadel in the Andes Mountains',
                'city' => 'Cusco',
                'country' => 'Peru',
                'latitude' => -13.1631,
                'longitude' => -72.5450,
                'category' => 'landmark',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Sydney Opera House',
                'description' => 'Multi-venue performing arts centre in Sydney',
                'city' => 'Sydney',
                'country' => 'Australia',
                'latitude' => -33.8568,
                'longitude' => 151.2153,
                'category' => 'landmark',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Sagrada Familia',
                'description' => 'Large unfinished Roman Catholic basilica designed by Gaudí',
                'city' => 'Barcelona',
                'country' => 'Spain',
                'latitude' => 41.4036,
                'longitude' => 2.1744,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Petra',
                'description' => 'Archaeological city famous for rock-cut architecture',
                'city' => 'Ma\'an',
                'country' => 'Jordan',
                'latitude' => 30.3285,
                'longitude' => 35.4444,
                'category' => 'landmark',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Acropolis of Athens',
                'description' => 'Ancient citadel on a rocky outcrop above Athens',
                'city' => 'Athens',
                'country' => 'Greece',
                'latitude' => 37.9715,
                'longitude' => 23.7267,
                'category' => 'landmark',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Christ the Redeemer',
                'description' => 'Art Deco statue of Jesus Christ in Rio de Janeiro',
                'city' => 'Rio de Janeiro',
                'country' => 'Brazil',
                'latitude' => -22.9519,
                'longitude' => -43.2105,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Angkor Wat',
                'description' => 'Temple complex and largest religious monument in the world',
                'city' => 'Siem Reap',
                'country' => 'Cambodia',
                'latitude' => 13.4125,
                'longitude' => 103.8670,
                'category' => 'landmark',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Neuschwanstein Castle',
                'description' => '19th-century Romanesque Revival palace in Bavaria',
                'city' => 'Schwangau',
                'country' => 'Germany',
                'latitude' => 47.5576,
                'longitude' => 10.7498,
                'category' => 'landmark',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Golden Gate Bridge',
                'description' => 'Iconic suspension bridge spanning the Golden Gate strait',
                'city' => 'San Francisco',
                'country' => 'United States',
                'latitude' => 37.8199,
                'longitude' => -122.4783,
                'category' => 'landmark',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Burj Khalifa',
                'description' => 'Tallest structure and building in the world',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'latitude' => 25.1972,
                'longitude' => 55.2744,
                'category' => 'landmark',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Mount Fuji',
                'description' => 'Active stratovolcano and highest mountain in Japan',
                'city' => 'Fujinomiya',
                'country' => 'Japan',
                'latitude' => 35.3606,
                'longitude' => 138.7274,
                'category' => 'nature',
                'rating' => 4.8,
                'image_url' => 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Niagara Falls',
                'description' => 'Group of three waterfalls at the border of Ontario and New York',
                'city' => 'Niagara Falls',
                'country' => 'Canada',
                'latitude' => 43.0896,
                'longitude' => -79.0849,
                'category' => 'nature',
                'rating' => 4.7,
                'image_url' => 'https://images.unsplash.com/photo-1489447068241-b3490214e879?w=800&h=600&fit=crop',
            ],
            [
                'name' => 'Grand Canyon',
                'description' => 'Steep-sided canyon carved by the Colorado River',
                'city' => 'Arizona',
                'country' => 'United States',
                'latitude' => 36.1069,
                'longitude' => -112.1129,
                'category' => 'nature',
                'rating' => 4.9,
                'image_url' => 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&h=600&fit=crop',
            ],
        ];

        foreach ($places as $place) {
            Place::create($place);
        }

        // Institutions
        $institutions = [
            // Museums
            [
                'name' => 'Louvre Museum',
                'description' => 'The world\'s largest art museum and a historic monument in Paris',
                'category' => 'museum',
                'address' => 'Rue de Rivoli, 75001',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8606,
                'longitude' => 2.3376,
                'rating' => 4.7,
            ],
            [
                'name' => 'British Museum',
                'description' => 'Public museum dedicated to human history, art and culture',
                'category' => 'museum',
                'address' => 'Great Russell St, London WC1B 3DG',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5194,
                'longitude' => -0.1270,
                'rating' => 4.6,
            ],
            [
                'name' => 'Metropolitan Museum of Art',
                'description' => 'The largest art museum in the United States',
                'category' => 'museum',
                'address' => '1000 5th Ave, New York, NY 10028',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7794,
                'longitude' => -73.9632,
                'rating' => 4.8,
            ],
            [
                'name' => 'Latvian National Museum of Art',
                'description' => 'The richest collection of national art in Latvia',
                'category' => 'museum',
                'address' => 'Jaņa Rozentāla laukums 1',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9548,
                'longitude' => 24.1141,
                'rating' => 4.5,
            ],
            [
                'name' => 'Prado Museum',
                'description' => 'Spain\'s main national art museum',
                'category' => 'museum',
                'address' => 'Calle de Ruiz de Alarcón, 23, 28014 Madrid',
                'city' => 'Madrid',
                'country' => 'Spain',
                'latitude' => 40.4138,
                'longitude' => -3.6921,
                'rating' => 4.7,
            ],
            [
                'name' => 'Uffizi Gallery',
                'description' => 'Prominent art museum in Florence',
                'category' => 'museum',
                'address' => 'Piazzale degli Uffizi, 6, 50122 Firenze',
                'city' => 'Florence',
                'country' => 'Italy',
                'latitude' => 43.7687,
                'longitude' => 11.2569,
                'rating' => 4.8,
            ],
            
            // Hotels
            [
                'name' => 'The Ritz Paris',
                'description' => 'Luxury hotel in the heart of Paris',
                'category' => 'hotel',
                'address' => '15 Place Vendôme, 75001',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8682,
                'longitude' => 2.3285,
                'rating' => 4.9,
            ],
            [
                'name' => 'The Savoy',
                'description' => 'Iconic luxury hotel on the Strand',
                'category' => 'hotel',
                'address' => 'Strand, London WC2R 0EZ',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5104,
                'longitude' => -0.1204,
                'rating' => 4.8,
            ],
            [
                'name' => 'Grand Hotel Riga',
                'description' => 'Historic luxury hotel in Riga',
                'category' => 'hotel',
                'address' => 'Aspazijas bulvāris 22',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9511,
                'longitude' => 24.1121,
                'rating' => 4.7,
            ],
            [
                'name' => 'Hotel Plaza Athénée',
                'description' => 'Luxury hotel on Avenue Montaigne',
                'category' => 'hotel',
                'address' => '25 Avenue Montaigne, 75008',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8661,
                'longitude' => 2.3048,
                'rating' => 4.8,
            ],
            
            // Restaurants
            [
                'name' => 'Le Jules Verne',
                'description' => 'Michelin-starred restaurant in the Eiffel Tower',
                'category' => 'restaurant',
                'address' => 'Avenue Gustave Eiffel, 75007',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8583,
                'longitude' => 2.2945,
                'rating' => 4.9,
            ],
            [
                'name' => 'Sketch',
                'description' => 'Quirky restaurant and afternoon tea venue',
                'category' => 'restaurant',
                'address' => '9 Conduit St, London W1S 2XG',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5136,
                'longitude' => -0.1410,
                'rating' => 4.6,
            ],
            [
                'name' => 'Vincents',
                'description' => 'Fine dining restaurant in Riga',
                'category' => 'restaurant',
                'address' => 'Elizabetes iela 19',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9548,
                'longitude' => 24.1167,
                'rating' => 4.7,
            ],
            [
                'name' => 'Osteria Francescana',
                'description' => 'Three Michelin star restaurant',
                'category' => 'restaurant',
                'address' => 'Via Stella, 22, 41121 Modena',
                'city' => 'Modena',
                'country' => 'Italy',
                'latitude' => 44.6471,
                'longitude' => 10.9252,
                'rating' => 5.0,
            ],
            [
                'name' => 'Eleven Madison Park',
                'description' => 'Fine dining restaurant in Manhattan',
                'category' => 'restaurant',
                'address' => '11 Madison Ave, New York, NY 10010',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7425,
                'longitude' => -73.9871,
                'rating' => 4.8,
            ],
            
            // Cafes
            [
                'name' => 'Café de Flore',
                'description' => 'Historic café in Saint-Germain-des-Prés',
                'category' => 'cafe',
                'address' => '172 Boulevard Saint-Germain, 75006',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8542,
                'longitude' => 2.3320,
                'rating' => 4.5,
            ],
            [
                'name' => 'Caffè Florian',
                'description' => 'Historic café in St Mark\'s Square',
                'category' => 'cafe',
                'address' => 'Piazza San Marco, 57, 30124 Venezia',
                'city' => 'Venice',
                'country' => 'Italy',
                'latitude' => 45.4338,
                'longitude' => 12.3378,
                'rating' => 4.6,
            ],
            [
                'name' => 'Miit Coffee',
                'description' => 'Specialty coffee shop in Riga',
                'category' => 'cafe',
                'address' => 'Tērbatas iela 41/43',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9577,
                'longitude' => 24.1211,
                'rating' => 4.7,
            ],
            [
                'name' => 'Blue Bottle Coffee',
                'description' => 'Artisanal coffee roaster and retailer',
                'category' => 'cafe',
                'address' => '450 W 15th St, New York, NY 10011',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7425,
                'longitude' => -74.0071,
                'rating' => 4.5,
            ],
            
            // Bars
            [
                'name' => 'Harry\'s New York Bar',
                'description' => 'Historic cocktail bar in Paris',
                'category' => 'bar',
                'address' => '5 Rue Daunou, 75002',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8693,
                'longitude' => 2.3318,
                'rating' => 4.6,
            ],
            [
                'name' => 'The American Bar',
                'description' => 'Legendary cocktail bar at The Savoy',
                'category' => 'bar',
                'address' => 'Strand, London WC2R 0EZ',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5104,
                'longitude' => -0.1204,
                'rating' => 4.7,
            ],
            [
                'name' => 'Skyline Bar',
                'description' => 'Rooftop bar with panoramic views',
                'category' => 'bar',
                'address' => 'Elizabetes iela 55',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9615,
                'longitude' => 24.1213,
                'rating' => 4.5,
            ],
            
            // Shops
            [
                'name' => 'Galeries Lafayette',
                'description' => 'Upscale French department store',
                'category' => 'shop',
                'address' => '40 Boulevard Haussmann, 75009',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8738,
                'longitude' => 2.3320,
                'rating' => 4.6,
            ],
            [
                'name' => 'Harrods',
                'description' => 'Luxury department store in Knightsbridge',
                'category' => 'shop',
                'address' => '87-135 Brompton Rd, London SW1X 7XL',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.4994,
                'longitude' => -0.1632,
                'rating' => 4.7,
            ],
            [
                'name' => 'Stockmann',
                'description' => 'Department store in central Riga',
                'category' => 'shop',
                'address' => '13. janvāra iela 8',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => 56.9496,
                'longitude' => 24.1163,
                'rating' => 4.4,
            ],
            [
                'name' => 'Macy\'s Herald Square',
                'description' => 'Iconic department store in Manhattan',
                'category' => 'shop',
                'address' => '151 W 34th St, New York, NY 10001',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7508,
                'longitude' => -73.9897,
                'rating' => 4.5,
            ],
            
            // Additional Museums
            [
                'name' => 'Vatican Museums',
                'description' => 'Public art and sculpture museums in Vatican City',
                'category' => 'museum',
                'address' => 'Viale Vaticano, 00165 Roma',
                'city' => 'Rome',
                'country' => 'Italy',
                'latitude' => 41.9065,
                'longitude' => 12.4536,
                'rating' => 4.7,
            ],
            [
                'name' => 'Hermitage Museum',
                'description' => 'Museum of art and culture in Saint Petersburg',
                'category' => 'museum',
                'address' => 'Palace Square, 2',
                'city' => 'Saint Petersburg',
                'country' => 'Russia',
                'latitude' => 59.9398,
                'longitude' => 30.3146,
                'rating' => 4.8,
            ],
            [
                'name' => 'Rijksmuseum',
                'description' => 'Dutch national museum dedicated to arts and history',
                'category' => 'museum',
                'address' => 'Museumstraat 1, 1071 XX Amsterdam',
                'city' => 'Amsterdam',
                'country' => 'Netherlands',
                'latitude' => 52.3600,
                'longitude' => 4.8852,
                'rating' => 4.7,
            ],
            [
                'name' => 'National Museum of China',
                'description' => 'Museum of Chinese art and history',
                'category' => 'museum',
                'address' => '16 East Chang\'an Avenue',
                'city' => 'Beijing',
                'country' => 'China',
                'latitude' => 39.9042,
                'longitude' => 116.3974,
                'rating' => 4.6,
            ],
            
            // Additional Hotels
            [
                'name' => 'Burj Al Arab',
                'description' => 'Luxury hotel on an artificial island',
                'category' => 'hotel',
                'address' => 'Jumeirah St, Dubai',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'latitude' => 25.1413,
                'longitude' => 55.1853,
                'rating' => 4.9,
            ],
            [
                'name' => 'Marina Bay Sands',
                'description' => 'Integrated resort with iconic rooftop',
                'category' => 'hotel',
                'address' => '10 Bayfront Ave',
                'city' => 'Singapore',
                'country' => 'Singapore',
                'latitude' => 1.2834,
                'longitude' => 103.8607,
                'rating' => 4.7,
            ],
            [
                'name' => 'The Plaza Hotel',
                'description' => 'Luxury hotel and landmark in Manhattan',
                'category' => 'hotel',
                'address' => 'Fifth Avenue at Central Park South',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7644,
                'longitude' => -73.9744,
                'rating' => 4.6,
            ],
            [
                'name' => 'Raffles Hotel',
                'description' => 'Colonial-style luxury hotel',
                'category' => 'hotel',
                'address' => '1 Beach Rd',
                'city' => 'Singapore',
                'country' => 'Singapore',
                'latitude' => 1.2946,
                'longitude' => 103.8540,
                'rating' => 4.7,
            ],
            
            // Additional Restaurants
            [
                'name' => 'Noma',
                'description' => 'Two Michelin star restaurant',
                'category' => 'restaurant',
                'address' => 'Refshalevej 96',
                'city' => 'Copenhagen',
                'country' => 'Denmark',
                'latitude' => 55.6961,
                'longitude' => 12.6113,
                'rating' => 4.9,
            ],
            [
                'name' => 'El Celler de Can Roca',
                'description' => 'Three Michelin star restaurant',
                'category' => 'restaurant',
                'address' => 'Carrer de Can Sunyer, 48',
                'city' => 'Girona',
                'country' => 'Spain',
                'latitude' => 41.9794,
                'longitude' => 2.8214,
                'rating' => 4.9,
            ],
            [
                'name' => 'Sukiyabashi Jiro',
                'description' => 'Three Michelin star sushi restaurant',
                'category' => 'restaurant',
                'address' => 'Tsukamoto Sogyo Building B1F',
                'city' => 'Tokyo',
                'country' => 'Japan',
                'latitude' => 35.6684,
                'longitude' => 139.7638,
                'rating' => 5.0,
            ],
            [
                'name' => 'The French Laundry',
                'description' => 'Three Michelin star French restaurant',
                'category' => 'restaurant',
                'address' => '6640 Washington St',
                'city' => 'Yountville',
                'country' => 'United States',
                'latitude' => 38.4024,
                'longitude' => -122.3625,
                'rating' => 4.8,
            ],
            
            // Additional Cafes
            [
                'name' => 'Café Central',
                'description' => 'Traditional Viennese coffeehouse',
                'category' => 'cafe',
                'address' => 'Herrengasse 14',
                'city' => 'Vienna',
                'country' => 'Austria',
                'latitude' => 48.2104,
                'longitude' => 16.3650,
                'rating' => 4.6,
            ],
            [
                'name' => 'Café Tortoni',
                'description' => 'Historic café in Buenos Aires',
                'category' => 'cafe',
                'address' => 'Av. de Mayo 825',
                'city' => 'Buenos Aires',
                'country' => 'Argentina',
                'latitude' => -34.6088,
                'longitude' => -58.3756,
                'rating' => 4.5,
            ],
            [
                'name' => 'Café Majestic',
                'description' => 'Belle Époque café in Porto',
                'category' => 'cafe',
                'address' => 'Rua Santa Catarina 112',
                'city' => 'Porto',
                'country' => 'Portugal',
                'latitude' => 41.1496,
                'longitude' => -8.6109,
                'rating' => 4.6,
            ],
            
            // Additional Bars
            [
                'name' => 'Employees Only',
                'description' => 'Speakeasy-style cocktail bar',
                'category' => 'bar',
                'address' => '510 Hudson St',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => 40.7339,
                'longitude' => -74.0062,
                'rating' => 4.7,
            ],
            [
                'name' => 'Artesian',
                'description' => 'Award-winning cocktail bar',
                'category' => 'bar',
                'address' => '1C Portland Pl',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => 51.5186,
                'longitude' => -0.1436,
                'rating' => 4.8,
            ],
            [
                'name' => 'Bar Hemingway',
                'description' => 'Legendary bar at the Ritz Paris',
                'category' => 'bar',
                'address' => '15 Place Vendôme',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => 48.8682,
                'longitude' => 2.3285,
                'rating' => 4.7,
            ],
        ];

        foreach ($institutions as $institution) {
            Institution::create($institution);
        }
    }
}
