<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlacesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('places')->delete();
        
        \DB::table('places')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Eiffel Tower',
                'description' => 'Iconic iron lattice tower on the Champ de Mars in Paris',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=800&h=600&fit=crop',
                'city' => 'Paris',
                'country' => 'France',
                'latitude' => '48.85840000',
                'longitude' => '2.29450000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Central Park',
                'description' => 'Large public park in Manhattan, New York City',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=800&h=600&fit=crop',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.78290000',
                'longitude' => '-73.96540000',
                'category' => 'park',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Colosseum',
                'description' => 'Ancient amphitheatre in the centre of Rome',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&h=600&fit=crop',
                'city' => 'Rome',
                'country' => 'Italy',
                'latitude' => '41.89020000',
                'longitude' => '12.49220000',
                'category' => 'landmark',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Big Ben',
                'description' => 'The Great Bell of the clock at the north end of the Palace of Westminster',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=600&fit=crop',
                'city' => 'London',
                'country' => 'United Kingdom',
                'latitude' => '51.50070000',
                'longitude' => '-0.12460000',
                'category' => 'landmark',
                'rating' => '4.60',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Riga Old Town',
                'description' => 'Historic centre and a UNESCO World Heritage Site',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1593659039409-c2e4f3e6c636?w=800&h=600&fit=crop',
                'city' => 'Riga',
                'country' => 'Latvia',
                'latitude' => '56.94960000',
                'longitude' => '24.10520000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Statue of Liberty',
                'description' => 'Colossal neoclassical sculpture on Liberty Island',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1569098644584-210bcd375b59?w=800&h=600&fit=crop',
                'city' => 'New York',
                'country' => 'United States',
                'latitude' => '40.68920000',
                'longitude' => '-74.04450000',
                'category' => 'landmark',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Taj Mahal',
                'description' => 'Ivory-white marble mausoleum in Agra',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&h=600&fit=crop',
                'city' => 'Agra',
                'country' => 'India',
                'latitude' => '27.17510000',
                'longitude' => '78.04210000',
                'category' => 'landmark',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Great Wall of China',
                'description' => 'Ancient series of fortifications in northern China',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop',
                'city' => 'Beijing',
                'country' => 'China',
                'latitude' => '40.43190000',
                'longitude' => '116.57040000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Machu Picchu',
                'description' => '15th-century Inca citadel in the Andes Mountains',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=800&h=600&fit=crop',
                'city' => 'Cusco',
                'country' => 'Peru',
                'latitude' => '-13.16310000',
                'longitude' => '-72.54500000',
                'category' => 'landmark',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Sydney Opera House',
                'description' => 'Multi-venue performing arts centre in Sydney',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1523059623039-a9ed027e7fad?w=800&h=600&fit=crop',
                'city' => 'Sydney',
                'country' => 'Australia',
                'latitude' => '-33.85680000',
                'longitude' => '151.21530000',
                'category' => 'landmark',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Sagrada Familia',
                'description' => 'Large unfinished Roman Catholic basilica designed by Gaudí',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=600&fit=crop',
                'city' => 'Barcelona',
                'country' => 'Spain',
                'latitude' => '41.40360000',
                'longitude' => '2.17440000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Petra',
                'description' => 'Archaeological city famous for rock-cut architecture',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1579606032821-4e6161c81bd3?w=800&h=600&fit=crop',
                'city' => 'Ma\'an',
                'country' => 'Jordan',
                'latitude' => '30.32850000',
                'longitude' => '35.44440000',
                'category' => 'landmark',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:00:59',
                'updated_at' => '2026-05-03 21:00:59',
                'user_id' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Acropolis of Athens',
                'description' => 'Ancient citadel on a rocky outcrop above Athens',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&h=600&fit=crop',
                'city' => 'Athens',
                'country' => 'Greece',
                'latitude' => '37.97150000',
                'longitude' => '23.72670000',
                'category' => 'landmark',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Christ the Redeemer',
                'description' => 'Art Deco statue of Jesus Christ in Rio de Janeiro',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&h=600&fit=crop',
                'city' => 'Rio de Janeiro',
                'country' => 'Brazil',
                'latitude' => '-22.95190000',
                'longitude' => '-43.21050000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Angkor Wat',
                'description' => 'Temple complex and largest religious monument in the world',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1551918120-9739cb430c6d?w=800&h=600&fit=crop',
                'city' => 'Siem Reap',
                'country' => 'Cambodia',
                'latitude' => '13.41250000',
                'longitude' => '103.86700000',
                'category' => 'landmark',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Neuschwanstein Castle',
                'description' => '19th-century Romanesque Revival palace in Bavaria',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=800&h=600&fit=crop',
                'city' => 'Schwangau',
                'country' => 'Germany',
                'latitude' => '47.55760000',
                'longitude' => '10.74980000',
                'category' => 'landmark',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Golden Gate Bridge',
                'description' => 'Iconic suspension bridge spanning the Golden Gate strait',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&h=600&fit=crop',
                'city' => 'San Francisco',
                'country' => 'United States',
                'latitude' => '37.81990000',
                'longitude' => '-122.47830000',
                'category' => 'landmark',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Burj Khalifa',
                'description' => 'Tallest structure and building in the world',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop',
                'city' => 'Dubai',
                'country' => 'United Arab Emirates',
                'latitude' => '25.19720000',
                'longitude' => '55.27440000',
                'category' => 'landmark',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Mount Fuji',
                'description' => 'Active stratovolcano and highest mountain in Japan',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800&h=600&fit=crop',
                'city' => 'Fujinomiya',
                'country' => 'Japan',
                'latitude' => '35.36060000',
                'longitude' => '138.72740000',
                'category' => 'nature',
                'rating' => '4.80',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Niagara Falls',
                'description' => 'Group of three waterfalls at the border of Ontario and New York',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1489447068241-b3490214e879?w=800&h=600&fit=crop',
                'city' => 'Niagara Falls',
                'country' => 'Canada',
                'latitude' => '43.08960000',
                'longitude' => '-79.08490000',
                'category' => 'nature',
                'rating' => '4.70',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Grand Canyon',
                'description' => 'Steep-sided canyon carved by the Colorado River',
                'address' => NULL,
                'type' => 'park',
                'image' => NULL,
                'image_url' => 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=800&h=600&fit=crop',
                'city' => 'Arizona',
                'country' => 'United States',
                'latitude' => '36.10690000',
                'longitude' => '-112.11290000',
                'category' => 'nature',
                'rating' => '4.90',
                'created_at' => '2026-05-03 21:01:00',
                'updated_at' => '2026-05-03 21:01:00',
                'user_id' => NULL,
            ),
        ));
        
        
    }
}